In [65]:
#Create 3 DataFrames and save them as CSV files
import pandas as pd

project_data = {
    "ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A004","A005"],
    "Project": ["Project 1","Project 2","Project 3","Project 4","Project 5",
                "Project 6","Project 7","Project 8","Project 9","Project 10",
                "Project 11","Project 12","Project 13","Project 14"],
    "Cost": [1002000,2000000,4500000,5500000,None,680000,400000,350000,None,300000,2000000,1000000,3000000,200000],
    "Status": ["Finished","Ongoing","Finished","Ongoing","Finished",
               "Failed","Finished","Failed","Ongoing","Finished",
               "Failed","Ongoing","Finished","Finished"]
}

project_df = pd.DataFrame(project_data)
project_df.to_csv("project.csv", index=False)


# ---------------- Employee DataFrame ----------------
employee_data = {
    "ID": ["A001","A002","A003","A004","A005"],
    "Name": ["John Alter","Alice Luxemburg","Tom Sebastine","Nina Adgra","Amy Johny"],
    "Gender": ["M","F","M","F","F"],
    "City": ["Paris","London","Berlin","Newyork","Madrid"],
    "Age": [25,27,29,31,30]
}

employee_df = pd.DataFrame(employee_data)
employee_df.to_csv("employee.csv", index=False)


# ---------------- Seniority Level DataFrame ----------------
seniority_data = {
    "ID": ["A001","A002","A003","A004","A005"],
    "Designation Level": [2,2,3,2,3]
}

seniority_df = pd.DataFrame(seniority_data)
seniority_df.to_csv("seniority.csv", index=False)

In [2]:
pd.read_csv("project.csv")

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [3]:
pd.read_csv("employee.csv")

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxemburg      F   London   27
2  A003    Tom Sebastine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [15]:
pd.read_csv("seniority.csv")

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [59]:
#Fill missing Cost values using average (must use for loop)
avg=project_df["Cost"].mean()
for i in range(len(project_df)):
    if pd.isna(project_df.loc[i,'Cost']):
        project_df.loc[i,'Cost']=avg
print(project_df)

      ID     Project          Cost    Status
0   A001   Project 1  1.002000e+06  Finished
1   A002   Project 2  2.000000e+06   Ongoing
2   A003   Project 3  4.500000e+06  Finished
3   A004   Project 4  5.500000e+06   Ongoing
4   A005   Project 5  1.744333e+06  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  1.744333e+06   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+05  Finished

In [66]:
#Split the name column in the Employee dataframe into two new columns “First Name”, and “Last Name” and remove the older “name” column.
first_names = []
last_names = []

for name in employee_df["Name"]:
    # Split the name using space
    parts = name.split(" ")
    # Append first part as first name
    first_names.append(parts[0])
    # Append second part as last name
    last_names.append(parts[1])
# Create new columns
employee_df["First Name"] = first_names
employee_df["Last Name"] = last_names

# Drop the old Name column
employee_df.drop(columns=["Name"], inplace=True)
print(employee_df)

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxemburg
2  A003      M   Berlin   29        Tom  Sebastine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [38]:
print(employee_df.loc[:, ['Age', 'City']])

   Age     City
0   25    Paris
1   27   London
2   29   Berlin
3   31  Newyork
4   30   Madrid

In [67]:
# Join all three dataframes in one single dataframe. Name it “Final” 
# Merge employee and seniority data
final_df = pd.merge(employee_df, seniority_df, on="ID", how="inner")

# Merge project data
final_df = pd.merge(final_df, project_df, on="ID", how="inner")

In [68]:
print(final_df)

      ID Gender     City  Age First Name  Last Name  Designation Level  \
0   A001      M    Paris   25       John      Alter                  2
1   A001      M    Paris   25       John      Alter                  2
2   A001      M    Paris   25       John      Alter                  2
3   A002      F   London   27      Alice  Luxemburg                  2
4   A002      F   London   27      Alice  Luxemburg                  2
5   A003      M   Berlin   29        Tom  Sebastine                  3
6   A003      M   Berlin   29        Tom  Sebastine                  3
7   A003      M   Berlin   29        Tom  Sebastine                  3
8   A004      F  Newyork   31       Nina      Adgra                  2
9   A004      F  Newyork   31       Nina      Adgra                  2
10  A004      F  Newyork   31       Nina      Adgra                  2
11  A005      F   Madrid   30        Amy      Johny                  3
12  A005      F   Madrid   30        Amy      Johny                  3
13  A005      F   Madrid   30        Amy      Johny                  3

       Project       Cost    Status
0    Project 1  1002000.0  Finished
1    Project 9        NaN   Ongoing
2   Project 11  2000000.0    Failed
3    Project 2  2000000.0   Ongoing
4    Project 6   680000.0    Failed
5    Project 3  4500000.0  Finished
6    Project 8   350000.0    Failed
7   Project 10   300000.0  Finished
8    Project 4  5500000.0   Ongoing
9   Project 12  1000000.0   Ongoing
10  Project 13  3000000.0  Finished
11   Project 5        NaN  Finished
12   Project 7   400000.0  Finished
13  Project 14   200000.0  Finished

In [69]:
#Add a new bonus column in the Final dataframe. Give a 5% bonus concerning project cost only to employees who have finished the projects. 
final_df['Bonus']=0
for i in range(len(final_df)):
    if final_df.loc[i, "Status"] == "Finished":
        final_df.loc[i, "Bonus"] = final_df.loc[i, "Cost"] * 0.05
print(final_df)

      ID Gender     City  Age First Name  Last Name  Designation Level  \
0   A001      M    Paris   25       John      Alter                  2
1   A001      M    Paris   25       John      Alter                  2
2   A001      M    Paris   25       John      Alter                  2
3   A002      F   London   27      Alice  Luxemburg                  2
4   A002      F   London   27      Alice  Luxemburg                  2
5   A003      M   Berlin   29        Tom  Sebastine                  3
6   A003      M   Berlin   29        Tom  Sebastine                  3
7   A003      M   Berlin   29        Tom  Sebastine                  3
8   A004      F  Newyork   31       Nina      Adgra                  2
9   A004      F  Newyork   31       Nina      Adgra                  2
10  A004      F  Newyork   31       Nina      Adgra                  2
11  A005      F   Madrid   30        Amy      Johny                  3
12  A005      F   Madrid   30        Amy      Johny                  3
13  A005      F   Madrid   30        Amy      Johny                  3

       Project       Cost    Status     Bonus
0    Project 1  1002000.0  Finished   50100.0
1    Project 9        NaN   Ongoing       0.0
2   Project 11  2000000.0    Failed       0.0
3    Project 2  2000000.0   Ongoing       0.0
4    Project 6   680000.0    Failed       0.0
5    Project 3  4500000.0  Finished  225000.0
6    Project 8   350000.0    Failed       0.0
7   Project 10   300000.0  Finished   15000.0
8    Project 4  5500000.0   Ongoing       0.0
9   Project 12  1000000.0   Ongoing       0.0
10  Project 13  3000000.0  Finished  150000.0
11   Project 5        NaN  Finished       NaN
12   Project 7   400000.0  Finished   20000.0
13  Project 14   200000.0  Finished   10000.0

In [70]:
#Demote the designation level by 1, whose projects have status “fail”. Delete the employees record whose designation level is above 4.
# Demote designation for failed projects
for i in range(len(final_df)):
    if final_df.loc[i, "Status"] == "Failed":
        final_df.loc[i, "Designation Level"] += 1

# Remove employees whose designation level > 4
final_df = final_df[final_df["Designation Level"] <= 4]

In [71]:
print(final_df)

      ID Gender     City  Age First Name  Last Name  Designation Level  \
0   A001      M    Paris   25       John      Alter                  2
1   A001      M    Paris   25       John      Alter                  2
2   A001      M    Paris   25       John      Alter                  3
3   A002      F   London   27      Alice  Luxemburg                  2
4   A002      F   London   27      Alice  Luxemburg                  3
5   A003      M   Berlin   29        Tom  Sebastine                  3
6   A003      M   Berlin   29        Tom  Sebastine                  4
7   A003      M   Berlin   29        Tom  Sebastine                  3
8   A004      F  Newyork   31       Nina      Adgra                  2
9   A004      F  Newyork   31       Nina      Adgra                  2
10  A004      F  Newyork   31       Nina      Adgra                  2
11  A005      F   Madrid   30        Amy      Johny                  3
12  A005      F   Madrid   30        Amy      Johny                  3
13  A005      F   Madrid   30        Amy      Johny                  3

       Project       Cost    Status     Bonus
0    Project 1  1002000.0  Finished   50100.0
1    Project 9        NaN   Ongoing       0.0
2   Project 11  2000000.0    Failed       0.0
3    Project 2  2000000.0   Ongoing       0.0
4    Project 6   680000.0    Failed       0.0
5    Project 3  4500000.0  Finished  225000.0
6    Project 8   350000.0    Failed       0.0
7   Project 10   300000.0  Finished   15000.0
8    Project 4  5500000.0   Ongoing       0.0
9   Project 12  1000000.0   Ongoing       0.0
10  Project 13  3000000.0  Finished  150000.0
11   Project 5        NaN  Finished       NaN
12   Project 7   400000.0  Finished   20000.0
13  Project 14   200000.0  Finished   10000.0

In [48]:
#Add “Mr.” and “Mrs.” to the first name column and drop the gender column. 
# Add title based on gender
for i in range(len(final_df)):
    if final_df.loc[i, "Gender"] == "M":
        final_df.loc[i, "First Name"] = "Mr. " + final_df.loc[i, "First Name"]
    else:
        final_df.loc[i, "First Name"] = "Mrs. " + final_df.loc[i, "First Name"]

# Drop gender column
final_df.drop(columns=["Gender"], inplace=True)

In [50]:
print(final_df)

      ID     City  Age  First Name  Last Name  Designation Level     Project  \
0   A001    Paris   25    Mr. John      Alter                  2   Project 1
1   A001    Paris   25    Mr. John      Alter                  2   Project 9
2   A001    Paris   25    Mr. John      Alter                  3  Project 11
3   A002   London   27  Mrs. Alice  Luxemburg                  2   Project 2
4   A002   London   27  Mrs. Alice  Luxemburg                  3   Project 6
5   A003   Berlin   29     Mr. Tom  Sebastine                  3   Project 3
6   A003   Berlin   29     Mr. Tom  Sebastine                  4   Project 8
7   A003   Berlin   29     Mr. Tom  Sebastine                  3  Project 10
8   A004  Newyork   31   Mrs. Nina      Adgra                  2   Project 4
9   A004  Newyork   31   Mrs. Nina      Adgra                  2  Project 12
10  A004  Newyork   31   Mrs. Nina      Adgra                  2  Project 13
11  A005   Madrid   30    Mrs. Amy      Johny                  3   Project 5
12  A005   Madrid   30    Mrs. Amy      Johny                  3   Project 7
13  A005   Madrid   30    Mrs. Amy      Johny                  3  Project 14

            Cost    Status          Bonus
0   1.002000e+06  Finished   50100.000000
1   1.744333e+06   Ongoing       0.000000
2   2.000000e+06    Failed       0.000000
3   2.000000e+06   Ongoing       0.000000
4   6.800000e+05    Failed       0.000000
5   4.500000e+06  Finished  225000.000000
6   3.500000e+05    Failed       0.000000
7   3.000000e+05  Finished   15000.000000
8   5.500000e+06   Ongoing       0.000000
9   1.000000e+06   Ongoing       0.000000
10  3.000000e+06  Finished  150000.000000
11  1.744333e+06  Finished   87216.666667
12  4.000000e+05  Finished   20000.000000
13  2.000000e+05  Finished   10000.000000

In [72]:
#Promote designation level by 1 for the employees whose age is more than 29 years using IF condition. 
# Promote based on age
for i in range(len(final_df)):
    if final_df.loc[i, "Age"] > 29:
        final_df.loc[i, "Designation Level"] -= 1
print(final_df)

      ID Gender     City  Age First Name  Last Name  Designation Level  \
0   A001      M    Paris   25       John      Alter                  2
1   A001      M    Paris   25       John      Alter                  2
2   A001      M    Paris   25       John      Alter                  3
3   A002      F   London   27      Alice  Luxemburg                  2
4   A002      F   London   27      Alice  Luxemburg                  3
5   A003      M   Berlin   29        Tom  Sebastine                  3
6   A003      M   Berlin   29        Tom  Sebastine                  4
7   A003      M   Berlin   29        Tom  Sebastine                  3
8   A004      F  Newyork   31       Nina      Adgra                  1
9   A004      F  Newyork   31       Nina      Adgra                  1
10  A004      F  Newyork   31       Nina      Adgra                  1
11  A005      F   Madrid   30        Amy      Johny                  2
12  A005      F   Madrid   30        Amy      Johny                  2
13  A005      F   Madrid   30        Amy      Johny                  2

       Project       Cost    Status     Bonus
0    Project 1  1002000.0  Finished   50100.0
1    Project 9        NaN   Ongoing       0.0
2   Project 11  2000000.0    Failed       0.0
3    Project 2  2000000.0   Ongoing       0.0
4    Project 6   680000.0    Failed       0.0
5    Project 3  4500000.0  Finished  225000.0
6    Project 8   350000.0    Failed       0.0
7   Project 10   300000.0  Finished   15000.0
8    Project 4  5500000.0   Ongoing       0.0
9   Project 12  1000000.0   Ongoing       0.0
10  Project 13  3000000.0  Finished  150000.0
11   Project 5        NaN  Finished       NaN
12   Project 7   400000.0  Finished   20000.0
13  Project 14   200000.0  Finished   10000.0

In [73]:
#Add the cost of all projects for each Employee and save it in new dataframe “TotalProjCost” with three columns ID, First Name, and Total cost
# Group by employee and sum cost
total_cost_df = final_df.groupby(["ID", "First Name"])["Cost"].sum().reset_index()

# Rename column
total_cost_df.rename(columns={"Cost": "TotalProjCost"}, inplace=True)
print(total_cost_df)

     ID First Name  TotalProjCost
0  A001       John      3002000.0
1  A002      Alice      2680000.0
2  A003        Tom      5150000.0
3  A004       Nina      9500000.0
4  A005        Amy       600000.0

In [74]:
#Print all the employee details whose city name contains the letter “o” in it.
# Filter cities containing letter 'o'
city_o_df = final_df[final_df["City"].str.contains("o", case=False)]

# Display result
city_o_df

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
3,A002,F,London,27,Alice,Luxemburg,2,Project 2,2000000.0,Ongoing,0.0
4,A002,F,London,27,Alice,Luxemburg,3,Project 6,680000.0,Failed,0.0
8,A004,F,Newyork,31,Nina,Adgra,1,Project 4,5500000.0,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,1,Project 12,1000000.0,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,1,Project 13,3000000.0,Finished,150000.0